[package]
name = "dust-desktop"
version = "0.0.0"
edition = "2021"
publish = false

[features]
debug-views = ["bitflags", "realfft", "dust-core/disasm", "dust-core/channel-audio-capture"]
log = ["slog", "slog-term", "slog-async", "slog-imgui", "dust-core/log"]

jit = ["dust-core/jit"]

pu-checks = ["dust-core/pu-checks"]

interp-timing-details = ["dust-core/interp-timing-details"]
interp-pipeline = ["dust-core/interp-pipeline"]
interp-pipeline-accurate-reloads = ["interp-pipeline", "dust-core/interp-pipeline-accurate-reloads"]
interp-arm9-interlocks = ["dust-core/interp-arm9-interlocks"]
interp-r15-write-checks = ["dust-core/interp-r15-write-checks"]

xq-audio = ["dust-core/xq-audio"]

discord-presence = ["discord-rpc"]
gdb-server = ["gdb-protocol", "dust-core/debugger-hooks"]

compile-shaders = ["shaderc"]

[dependencies]
dust-core = { path = "../../core" }
dust-soft-3d = { path = "../../soft-3d" }
bitflags = { version = "1.3", optional = true }
ahash = "0.7"
winit = { version = "0.26", features = ["serde"] }
wgpu = { version = "0.12", features = ["spirv"] }
futures-executor = "0.3"
# TODO: Switch to imgui 0.9 when it's released with the docking API
imgui = { git = "https://github.com/imgui-rs/imgui-rs", features = ["docking", "tables-api"] }
imgui-winit-support = { git = "https://github.com/imgui-rs/imgui-rs" }
crossbeam-channel = "0.5"
slog = { version = "2.7", optional = true }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
slog-term = { version = "2.8", optional = true }
slog-async = { version = "2.6", optional = true }
slog-imgui = { git = "https://github.com/Kelpsy/slog-imgui", features = ["async"], optional = true }
rfd = "0.8"
home = "0.5"
parking_lot = "0.12"
cpal = "0.13"
chrono = { version = "0.4", features = ["serde"] }
discord-rpc = { git = "https://github.com/Kelpsy/discord-rpc", optional = true }
imgui-memory-editor = { git = "https://github.com/Kelpsy/imgui-memory-editor" }
gdb-protocol = { version = "0.1", optional = true }
libc = "0.2"
copypasta = "0.8"
realfft = { version = "3.0", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
objc = "0.2"

[build-dependencies]
shaderc = { version = "0.8", optional = true }
